- clean:
  - '~/.oh-my-zsh/custom/'
  - '~/.oh-my-zsh/custom/plugins/'
  - '~/.oh-my-zsh/custom/themes/'
- shell:
  - ['sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --skip-chsh', Installing Oh My Zsh]
- link:
    ~/.oh-my-zsh/custom/base16-shell_settings.zsh: shells/zsh/oh-my-zsh/custom/base16-shell_settings.zsh
    ~/.oh-my-zsh/custom/powerlevel9k_settings.zsh: shells/zsh/oh-my-zsh/custom/powerlevel9k_settings.zsh
    ~/.oh-my-zsh/custom/vi-mode_settings.zsh: shells/zsh/oh-my-zsh/custom/vi-mode_settings.zsh
    ~/.oh-my-zsh/custom/plugins/base16-shell: shells/zsh/oh-my-zsh/custom/plugins/base16-shell
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: shells/zsh/oh-my-zsh/custom/plugins/zsh-autosuggestions
    ~/.oh-my-zsh/custom/plugins/zsh-completions: shells/zsh/oh-my-zsh/custom/plugins/zsh-completions
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: shells/zsh/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    ~/.oh-my-zsh/custom/themes/powerlevel9k: shells/zsh/oh-my-zsh/custom/themes/powerlevel9k
    ~/.oh-my-zsh/custom/themes/powerlevel10k: shells/zsh/oh-my-zsh/custom/themes/powerlevel10k
