- clean:
    - '~/.oh-my-zsh/custom/'
    - '~/.oh-my-zsh/custom/plugins/'
    - '~/.oh-my-zsh/custom/themes/'
- shell:
    - description: Installing Oh My Zsh
      command: if [ ! -d "$HOME/.oh-my-zsh" ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" --skip-chsh; else true; fi
      quiet: true
- link:
    ~/.oh-my-zsh/custom/powerlevel9k.settings.zsh: shells/zsh/oh-my-zsh/custom/powerlevel9k.settings.zsh
    ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: shells/zsh/oh-my-zsh/custom/plugins/zsh-autosuggestions
    ~/.oh-my-zsh/custom/plugins/zsh-completions: shells/zsh/oh-my-zsh/custom/plugins/zsh-completions
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: shells/zsh/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    ~/.oh-my-zsh/custom/themes/powerlevel9k: shells/zsh/oh-my-zsh/custom/themes/powerlevel9k
    ~/.oh-my-zsh/custom/themes/powerlevel10k: shells/zsh/oh-my-zsh/custom/themes/powerlevel10k
