- clean:
    - '~/.vim'
    - '~/.vimrc'
- link:
    ~/.vim: editors/vim
    ~/.vimrc: editors/vim/vimrc
- shell:
    - description: Installing Vundle plugins
      command: vim +PluginInstall +qall
      quiet: false
      stdout: true
      stderr: true
