- clean:
    - '~/.vscode'
- vscode:
    # Editorconfig
    editorconfig.editorconfig:
      status: install
    # Code Formatter
    esbenp.prettier-vscode:
      status: install
    # Code Spell Checker
    streetsidesoftware.code-spell-checker:
      status: install
    # Show errors in the editor
    usernamehw.errorlens:
      status: install
    # Theme
    golf1052.base16-generator:
      status: install
    # Icons
    pkief.material-icon-theme:
      status: install
    # Git Support
    eamodio.gitlens:
      status: install
    # Gist Support
    vsls-contrib.gistfs:
      status: install
    # Markdown Lint
    DavidAnson.vscode-markdownlint:
      status: install
    # Markdown Support
    yzhang.markdown-all-in-one:
      status: install
    # Image Paste Support
    mushan.vscode-paste-image:
      status: install
    # Autocomplete
    VisualStudioExptTeam.vscodeintellicode:
      status: install
    # Remote development
    ms-vscode-remote.vscode-remote-extensionpack:
      status: install
    # Docker
    ms-azuretools.vscode-docker:
      status: install
    # C++ language support
    ms-vscode.cpptools:
      status: install
    # Rust language support
    rust-lang.rust:
      status: install
    # Python language support
    ms-python.python:
      status: install
    # Go language support
    ms-vscode.Go:
      status: install
    # Yaml support
    redhat.vscode-yaml:
      status: install
    XadillaX.viml:
      status: install
    # Vagrant support
    bbenoist.vagrant:
      status: install
