- brew:
    - mas # CLI for the Mac App Store
    - youtube-dl # command line video downloader
    - gallery-dl # command line gallery downloader
- cask:
    - the-unarchiver # Decompressing utility
    - stats # shows mac stats
    - spotify # Music streaming
    - 1password # Password manager
    - google-drive # Google Drive client
